[package]
name = "p2p-tor"
version = "0.1.0"
edition = "2024"

[dependencies]
p2p-core = { path = "../p2p-core" }
tokio = { workspace = true }
arti-client = { workspace = true }
tor-rtcompat = { workspace = true }
